__author__ = 'alisonbento'

STATUS_GENERAL_ERROR = 0

STATUS_OK = 200

STATUS_INVALID_REQUEST = 300
STATUS_INCORRECT_ARGS = 301
STATUS_LOGIN_FAIL = 302

STATUS_TOKEN_SUCCESS = 210
STATUS_TOKEN_FAILED = 310
STATUS_TOKEN_INVALID = 311
