__author__ = 'alisonbento'

STATUS_GENERAL_ERROR = 0

STATUS_OK = 100

STATUS_INVALID_REQUEST = 200
STATUS_INCORRECT_ARGS = 201
STATUS_LOGIN_FAIL = 202

STATUS_TOKEN_SUCCESS = 110
STATUS_TOKEN_FAILED = 210
STATUS_TOKEN_INVALID = 211
