__author__ = 'alisonbento'

STATUS_GENERAL_ERROR = (0, 'GENERAL ERROR')

STATUS_OK = (200, 'OK')

STATUS_INVALID_REQUEST = (300, 'INVALID REQUEST - NO SUCH METHOD FOR RESOURCE')
STATUS_INCORRECT_ARGS = (301, 'INCORRECT (OR MISSING) REQUEST ARGS')
STATUS_LOGIN_FAIL = (302, 'COULD NOT AUTHENTICATE USER - INCORRECT CREDENTIALS')

STATUS_TOKEN_SUCCESS = (210, 'TOKEN CREATED SUCCESSFULLY')
STATUS_TOKEN_FAILED = (310, 'COULD NOT CREATE TOKEN')
STATUS_TOKEN_INVALID = (311, 'TOKEN EXPIRED OR INEXISTENT')

STATUS_APPLIANCE_NOT_FOUND = (320, 'APPLIANCE NOT FOUND')
STATUS_APPLIANCE_UNREACHABLE = (321, 'APPLIANCE UNREACHEABLE OR NOT CONNECTED TO NETWORK')

STATUS_SERVICE_NOT_FOUND = (330, 'SERVICE NOT FOUND')
STATUS_STATUS_NOT_FOUND = (341, 'STATUS NOT FOUND')

STATUS_SERVICE_REQUIRE_PARAMETER = (331, 'SERVICE REQUIRE PARAMETERS')
