__author__ = 'alisonbento'

STATUS_GENERAL_ERROR = 0

STATUS_OK = 200

STATUS_INVALID_REQUEST = 300
STATUS_INCORRECT_ARGS = 301
STATUS_LOGIN_FAIL = 302

STATUS_TOKEN_SUCCESS = 210
STATUS_TOKEN_FAILED = 310
STATUS_TOKEN_INVALID = 311

STATUS_APPLIANCE_NOT_FOUND = 320
STATUS_APPLIANCE_UNREACHABLE = 321

STATUS_SERVICE_NOT_FOUND = 330
STATUS_STATUS_NOT_FOUND = 341

RES_DICT = {
    STATUS_OK: 'OK',
    STATUS_GENERAL_ERROR: 'GENERAL_ERROR',
    STATUS_INVALID_REQUEST: 'INVALID REQUEST - NO SUCH METHOD FOR RESOURCE',
    STATUS_INCORRECT_ARGS: 'INCORRECT (OR MISSING) REQUEST ARGS',
    STATUS_LOGIN_FAIL: 'COULD NOT AUTHENTICATE USER - INCORRECT CREDENTIALS',
    STATUS_TOKEN_SUCCESS: 'TOKEN CREATED SUCCESSFULLY',
    STATUS_TOKEN_FAILED: 'COULD NOT CREATE TOKEN',
    STATUS_TOKEN_INVALID: 'TOKEN EXPIRED OR INEXISTENT',
    STATUS_APPLIANCE_NOT_FOUND: 'APPLIANCE NOT FOUND',
    STATUS_APPLIANCE_UNREACHABLE: 'APPLIANCE UNREACHEABLE OR NOT CONNECTED TO NETWORK',
    STATUS_SERVICE_NOT_FOUND: 'SERVICE NOT FOUND',
    STATUS_STATUS_NOT_FOUND: 'STATUS NOT FOUND'

}